# -*- coding: utf-8 -*-
"""freight_rate_ml_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aYYrTRmm7-Jmh1S3RxpPaS2dagyAIkp
"""

# DATA LOADING
# ============================================================
# Load all datasets needed for the freight rate prediction task.
#
# train_test.csv:
#   Historical data containing the target variable: posted_rate
#
# validation.csv:
#   Unseen loads for which we must generate predicted_rate
#
# december-chart-inputs (1).csv:
#   Fixed December 2025 scenarios used for the required chart


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the training dataset
train = pd.read_csv("/content/train-test.csv")

# Load the validation dataset
validation = pd.read_csv("/content/validation.csv")

# Load the December prediction dataset
december = pd.read_csv("/content/december-chart-inputs (1).csv")

# Display the dimensions of each dataset
print("DATASET SHAPES")
print("=" * 60)
print("Training dataset:  ", train.shape)
print("Validation dataset:", validation.shape)
print("December dataset:  ", december.shape)

# Confirm that all datasets were loaded successfully
print("\nDATASETS LOADED SUCCESSFULLY.")

import pandas as pd
import numpy as np

train = pd.read_csv("train-test.csv")

print("Shape:", train.shape)
print("\nColumns:")
print(train.columns.tolist())

print("\nFirst 5 rows:")
display(train.head())

print("DATASET INFO")
print("=" * 50)
train.info()

print("\n\nMISSING VALUES")
print("=" * 50)
print(train.isnull().sum())

print("\n\nDUPLICATE ROWS")
print("=" * 50)
print("Number of duplicate rows:", train.duplicated().sum())

print("\n\nTARGET SUMMARY")
print("=" * 50)
print(train["posted_rate"].describe())

print("UNIQUE VALUES")
print("=" * 60)

for column in train.columns:
    print(f"\n{column}")
    print(f"Unique values: {train[column].nunique()}")

    if train[column].nunique() <= 20:
        print(train[column].value_counts())

print("DATA TYPES")
print("=" * 60)
print(train.dtypes)

print("CORRELATION WITH POSTED RATE")
print("=" * 60)

numeric_columns = train.select_dtypes(include=np.number).columns

correlation = (
    train[numeric_columns]
    .corr()["posted_rate"]
    .sort_values(ascending=False)
)

print(correlation)

# 1. NUMERICAL FEATURE SUMMARY

# We first inspect the main numerical variables in the dataset.
# This helps us understand their scale, variation, and possible
# data-quality issues before building any machine learning model.

import matplotlib.pyplot as plt
import seaborn as sns

# Select the numerical columns that are relevant to the analysis.
numeric_cols = [
    "distance",
    "weight",
    "market_index",
    "quote_signal",
    "posted_rate"
]

# Display descriptive statistics such as:
# count, mean, standard deviation, minimum,
# quartiles, and maximum.
print("NUMERICAL FEATURE SUMMARY")
display(train[numeric_cols].describe().T)

# 2. TARGET VARIABLE DISTRIBUTION

# 'posted_rate' is our target variable.
# We visualize its distribution to understand:
# - where most freight rates are concentrated
# - how spread out the rates are
# - whether there are very high or low values
# - whether the target appears skewed

plt.figure(figsize=(10, 5))

sns.histplot(
    train["posted_rate"],
    bins=60,
    kde=True
)

plt.title("Distribution of Posted Freight Rate")
plt.xlabel("Posted Rate ($)")
plt.ylabel("Number of Loads")

plt.show()

# 3. INVESTIGATE SUSPICIOUS WEIGHT VALUES

# The descriptive statistics show that the minimum
# weight is negative. Since shipment weight should
# normally be positive, we investigate these records
# before deciding how to handle them.

# Find rows where the shipment weight is zero or negative.
invalid_weight_rows = train[train["weight"] <= 0]

print(f"Number of non-positive weight records: {len(invalid_weight_rows)}")

# Display the affected records so we can understand
# whether the values are errors or follow a pattern.
display(
    invalid_weight_rows[
        [
            "load_id",
            "pickup",
            "delivery",
            "distance",
            "equipment",
            "weight",
            "date",
            "market_index",
            "quote_signal",
            "posted_rate"
        ]
    ].head(20)
)

# 4. INVESTIGATE WEIGHT DATA QUALITY

# We found negative weight values, which are not physically
# meaningful for a freight shipment.
#
# Before deciding how to clean them, we compare:
# 1. Missing weights
# 2. Negative weights
# 3. Valid positive weights
#
# This helps us understand the scale of the data-quality issue.

missing_weight = train["weight"].isna().sum()
negative_weight = (train["weight"] < 0).sum()
zero_weight = (train["weight"] == 0).sum()
positive_weight = (train["weight"] > 0).sum()

print("WEIGHT DATA QUALITY")
print("=" * 50)

print(f"Missing weights:      {missing_weight:,}")
print(f"Negative weights:     {negative_weight:,}")
print(f"Zero weights:         {zero_weight:,}")
print(f"Positive weights:     {positive_weight:,}")
print(f"Total rows:           {len(train):,}")

# Compare the posted freight rate across the different
# weight-quality groups.
#
# We are not using this to decide the treatment yet.
# We are simply checking whether these groups behave differently.

train["weight_status"] = np.select(
    [
        train["weight"].isna(),
        train["weight"] < 0,
        train["weight"] == 0,
        train["weight"] > 0
    ],
    [
        "Missing",
        "Negative",
        "Zero",
        "Positive"
    ],
    default="Unknown"
)

print("\nAVERAGE POSTED RATE BY WEIGHT STATUS")
display(
    train.groupby("weight_status")["posted_rate"]
    .agg(["count", "mean", "median"])
    .sort_values("count", ascending=False)
)

# 5. CHECK WEIGHT QUALITY IN OTHER DATASETS

# We identified missing and negative weights in the training data.
# Before deciding on the final preprocessing pipeline, we need to
# check whether the same issue appears in the validation data.
#
# This is important because the same preprocessing must work
# consistently on both training and unseen data.

print("WEIGHT QUALITY CHECK")
print("=" * 50)

# Check the validation dataset
validation_missing = validation["weight"].isna().sum()
validation_negative = (validation["weight"] < 0).sum()
validation_zero = (validation["weight"] == 0).sum()

print("\nVALIDATION DATA")
print(f"Missing weights:  {validation_missing:,}")
print(f"Negative weights: {validation_negative:,}")
print(f"Zero weights:     {validation_zero:,}")
print(f"Total rows:       {len(validation):,}")

# Check the December dataset
december_missing = december["weight"].isna().sum()
december_negative = (december["weight"] < 0).sum()
december_zero = (december["weight"] == 0).sum()

print("\nDECEMBER DATA")
print(f"Missing weights:  {december_missing:,}")
print(f"Negative weights: {december_negative:,}")
print(f"Zero weights:     {december_zero:,}")
print(f"Total rows:       {len(december):,}")

# INVALID WEIGHT INSPECTION

# We inspect invalid weight values before deciding how to
# preprocess them. We do not remove any records at this stage.

invalid_weight_train = train[
    train["weight"].isna() | (train["weight"] < 0)
]

print("INVALID WEIGHTS IN TRAINING DATA")
print("=" * 60)
print("Number of invalid records:", len(invalid_weight_train))

print("\nWeight statistics for invalid records:")
print(invalid_weight_train["weight"].describe())

print("\nSample of invalid weight records:")
display(
    invalid_weight_train[
        ["load_id", "pickup", "delivery", "distance",
         "equipment", "weight", "date", "posted_rate"]
    ].head(20)
)

# ============================================================
# INVALID WEIGHT VS VALID WEIGHT
# ============================================================
# Compare the main numerical variables between valid and
# invalid weight records. This helps us decide how to treat
# the corrupted weight values during preprocessing.

train_check = train.copy()

# Create a simple weight-quality label
train_check["weight_status"] = np.where(
    train_check["weight"].isna(),
    "Missing",
    np.where(
        train_check["weight"] < 0,
        "Negative",
        "Positive"
    )
)

# Compare the main numerical variables
comparison = (
    train_check
    .groupby("weight_status")[
        ["distance", "market_index", "quote_signal", "posted_rate"]
    ]
    .agg(["count", "mean", "median"])
    .round(2)
)

print("COMPARISON BY WEIGHT STATUS")
print("=" * 70)

display(comparison)

# Compare equipment types across the three weight-quality groups

equipment_comparison = pd.crosstab(
    train_check["equipment"],
    train_check["weight_status"],
    normalize="columns"
).round(3)

print("EQUIPMENT DISTRIBUTION BY WEIGHT STATUS")
print("=" * 70)

display(equipment_comparison)

# ============================================================
# WEIGHT CLEANING
# ============================================================
# Negative weights are not physically meaningful for freight
# loads, so they are treated as missing values.
#
# We keep the affected rows because the other features still
# contain useful information and the assessment requires
# predictions for every validation load.

train_clean = train.copy()
validation_clean = validation.copy()
december_clean = december.copy()

# Convert negative weights to missing values
train_clean.loc[train_clean["weight"] < 0, "weight"] = np.nan
validation_clean.loc[validation_clean["weight"] < 0, "weight"] = np.nan
december_clean.loc[december_clean["weight"] < 0, "weight"] = np.nan

print("WEIGHT CLEANING SUMMARY")
print("=" * 60)

print("\nTraining:")
print("Missing weights after cleaning:",
      train_clean["weight"].isna().sum())

print("\nValidation:")
print("Missing weights after cleaning:",
      validation_clean["weight"].isna().sum())

print("\nDecember:")
print("Missing weights after cleaning:",
      december_clean["weight"].isna().sum())

# ============================================================
# DATE FEATURE INSPECTION
# ============================================================
# Convert the date column to datetime so we can examine the
# temporal structure of the dataset.

train_clean["date"] = pd.to_datetime(train_clean["date"])
validation_clean["date"] = pd.to_datetime(validation_clean["date"])
december_clean["date"] = pd.to_datetime(december_clean["date"])

print("DATE RANGE")
print("=" * 60)

print("Training:")
print("Start:", train_clean["date"].min())
print("End:  ", train_clean["date"].max())

print("\nValidation:")
print("Start:", validation_clean["date"].min())
print("End:  ", validation_clean["date"].max())

print("\nDecember:")
print("Start:", december_clean["date"].min())
print("End:  ", december_clean["date"].max())

# Check the number of training records per day
daily_counts = train_clean.groupby("date").size()

print("\nTRAINING RECORDS PER DAY")
print("=" * 60)
print("Minimum:", daily_counts.min())
print("Maximum:", daily_counts.max())
print("Average:", round(daily_counts.mean(), 2))

display(daily_counts.head(10))

# ============================================================
# TIME-BASED TRAIN / VALIDATION SPLIT
# ============================================================
# We use a chronological split instead of a random split.
# This better represents the real prediction task:
# training on earlier loads and validating on later loads.
# ============================================================

# Make sure the date column is stored as datetime
train["date"] = pd.to_datetime(train["date"])

# Sort the data chronologically
train = train.sort_values("date").reset_index(drop=True)

# Find the date that separates the first 80% from the last 20%
split_index = int(len(train) * 0.80)

# Create chronological training and validation sets
model_train = train.iloc[:split_index].copy()
model_valid = train.iloc[split_index:].copy()

print("TIME-BASED DATA SPLIT")
print("=" * 55)

print("\nModel training period:")
print("Start:", model_train["date"].min())
print("End:  ", model_train["date"].max())
print("Rows:", f"{len(model_train):,}")

print("\nModel validation period:")
print("Start:", model_valid["date"].min())
print("End:  ", model_valid["date"].max())
print("Rows:", f"{len(model_valid):,}")

print("\nValidation percentage:",
      f"{len(model_valid) / len(train) * 100:.1f}%")

# ============================================================
# STRICT DATE-BASED TRAIN / VALIDATION SPLIT
# ============================================================
# We split by calendar date so that no date appears in both
# the training and validation sets.
# ============================================================

split_date = pd.Timestamp("2025-09-01")

model_train = train[train["date"] < split_date].copy()
model_valid = train[train["date"] >= split_date].copy()

print("STRICT TIME-BASED DATA SPLIT")
print("=" * 55)

print("\nModel training period:")
print("Start:", model_train["date"].min())
print("End:  ", model_train["date"].max())
print("Rows:", f"{len(model_train):,}")

print("\nModel validation period:")
print("Start:", model_valid["date"].min())
print("End:  ", model_valid["date"].max())
print("Rows:", f"{len(model_valid):,}")

print("\nValidation percentage:",
      f"{len(model_valid) / len(train) * 100:.1f}%")

# Confirm that the two periods do not overlap
overlap = set(model_train["date"]).intersection(set(model_valid["date"]))

print("\nDate overlap:", len(overlap))

# ============================================================
# CLEAN WEIGHT VALUES
# ============================================================
# A load weight cannot be negative.
# We therefore treat negative weights as missing values.
# Missing values will be handled during preprocessing.
# ============================================================

# Create copies so the original datasets remain unchanged
model_train = model_train.copy()
model_valid = model_valid.copy()
december = december.copy()

# Convert negative weights to NaN
model_train.loc[model_train["weight"] < 0, "weight"] = np.nan
model_valid.loc[model_valid["weight"] < 0, "weight"] = np.nan
december.loc[december["weight"] < 0, "weight"] = np.nan

print("WEIGHT CLEANING")
print("=" * 55)

print("\nTraining:")
print("Missing weights:", model_train["weight"].isna().sum())

print("\nValidation:")
print("Missing weights:", model_valid["weight"].isna().sum())

print("\nDecember:")
print("Missing weights:", december["weight"].isna().sum())

# ============================================================
# CHECK MISSING VALUES IN NUMERICAL FEATURES
# ============================================================
# Training and validation contain the full set of model
# features. The December file has a smaller set of fixed
# columns, so we check only the columns available in each file.
# ============================================================

# Numerical features available in the training/validation data
model_features = [
    "pickup_lat",
    "pickup_lon",
    "delivery_lat",
    "delivery_lon",
    "distance",
    "weight",
    "market_index",
    "quote_signal"
]

# Numerical columns available in the December prediction file
december_features = [
    "distance",
    "weight"
]

print("MISSING VALUES AFTER DATA SPLIT AND WEIGHT CLEANING")
print("=" * 60)

print("\nTraining data:")
print(model_train[model_features].isna().sum())

print("\nValidation data:")
print(model_valid[model_features].isna().sum())

print("\nDecember data:")
print(december[december_features].isna().sum())

# ============================================================
# HANDLE MISSING NUMERICAL VALUES
# ============================================================
# We calculate imputation values using ONLY the model-training
# data. The same values are then applied to validation data.
# This prevents information leakage from the validation period.
# ============================================================

# Calculate medians from training data only
weight_median = model_train["weight"].median()
market_index_median = model_train["market_index"].median()

print("IMPUTATION VALUES FROM TRAINING DATA")
print("=" * 55)
print(f"Weight median: {weight_median:.2f}")
print(f"Market index median: {market_index_median:.4f}")

# Fill missing values in the training data
model_train["weight"] = model_train["weight"].fillna(weight_median)
model_train["market_index"] = model_train["market_index"].fillna(
    market_index_median
)

# Apply the SAME training medians to validation data
model_valid["weight"] = model_valid["weight"].fillna(weight_median)
model_valid["market_index"] = model_valid["market_index"].fillna(
    market_index_median
)

print("\nMISSING VALUES AFTER IMPUTATION")
print("=" * 55)

print("\nTraining:")
print(model_train[["weight", "market_index"]].isna().sum())

print("\nValidation:")
print(model_valid[["weight", "market_index"]].isna().sum())

# ============================================================
# FEATURE ENGINEERING
# ============================================================
# Convert the date into separate calendar features and create
# a route identifier from pickup and delivery locations.
# ============================================================

def create_features(data):
    """Create model-ready features from the raw dataset."""

    data = data.copy()

    # Make sure date is stored as datetime
    data["date"] = pd.to_datetime(data["date"])

    # Calendar features
    data["year"] = data["date"].dt.year
    data["month"] = data["date"].dt.month
    data["day"] = data["date"].dt.day
    data["day_of_week"] = data["date"].dt.dayofweek
    data["day_of_year"] = data["date"].dt.dayofyear
    data["week_of_year"] = data["date"].dt.isocalendar().week.astype(int)

    # Route identifier
    data["route"] = data["pickup"] + " -> " + data["delivery"]

    return data


# Apply the same feature engineering to both datasets
model_train = create_features(model_train)
model_valid = create_features(model_valid)

print("FEATURE ENGINEERING")
print("=" * 55)

print("\nNew features:")
print([
    "year",
    "month",
    "day",
    "day_of_week",
    "day_of_year",
    "week_of_year",
    "route"
])

print("\nTraining shape:", model_train.shape)
print("Validation shape:", model_valid.shape)

print("\nSample of engineered features:")
display(
    model_train[
        [
            "date",
            "pickup",
            "delivery",
            "route",
            "month",
            "day_of_week",
            "day_of_year"
        ]
    ].head()
)

# Check the columns available in the external validation dataset.
# This dataset is used later for the final predictions, so it does not
# contain the target variable posted_rate.

print("Validation dataset columns:")
print(validation.columns.tolist())

print("\nValidation shape:")
print(validation.shape)

# Create a time-based validation split from the labeled training data.
# The model will learn from earlier dates and be evaluated on later dates.
# This better reflects the real forecasting situation.

train_model = train[
    train["date"] < "2025-09-01"
].copy()

model_validation = train[
    train["date"] >= "2025-09-01"
].copy()

print("TIME-BASED MODEL SPLIT")
print("=" * 60)

print("\nModel training data:")
print("Rows:", len(train_model))
print("Start:", train_model["date"].min())
print("End:", train_model["date"].max())

print("\nModel validation data:")
print("Rows:", len(model_validation))
print("Start:", model_validation["date"].min())
print("End:", model_validation["date"].max())

print("\nValidation percentage:",
      round(len(model_validation) / len(train) * 100, 1), "%")

# Create one feature-engineering function so that the same transformations
# are applied consistently to training, validation, and December data.

def create_features(df):
    data = df.copy()

    # Convert date to datetime so we can extract calendar information.
    data["date"] = pd.to_datetime(data["date"])

    # Calendar-based features.
    data["year"] = data["date"].dt.year
    data["month"] = data["date"].dt.month
    data["day"] = data["date"].dt.day
    data["day_of_week"] = data["date"].dt.dayofweek
    data["day_of_year"] = data["date"].dt.dayofyear
    data["week_of_year"] = data["date"].dt.isocalendar().week.astype(int)

    # Represent the origin-destination combination as a route feature.
    data["route"] = data["pickup"] + " -> " + data["delivery"]

    return data


# Apply the same feature engineering to each dataset.
train_model_features = create_features(train_model)
validation_features = create_features(model_validation)
assessment_features = create_features(validation)
december_features = create_features(december)

print("FEATURE ENGINEERING")
print("=" * 60)

print("\nTraining:", train_model_features.shape)
print("Internal validation:", validation_features.shape)
print("Assessment validation:", assessment_features.shape)
print("December:", december_features.shape)

print("\nNew features:")
print([
    "year",
    "month",
    "day",
    "day_of_week",
    "day_of_year",
    "week_of_year",
    "route"
])

# Prepare the model inputs.
# CatBoost can work directly with categorical features, so we keep
# pickup, delivery, equipment, and route as categorical variables.

target = "posted_rate"

# Columns that should not be used as model predictors.
drop_columns = ["load_id", "date", target]

X_train_model = train_model_features.drop(columns=drop_columns)
y_train_model = train_model_features[target]

X_val_model = validation_features.drop(columns=drop_columns)
y_val_model = validation_features[target]

# Identify categorical columns.
categorical_columns = [
    "pickup",
    "delivery",
    "equipment",
    "route"
]

print("MODEL PREPARATION")
print("=" * 60)

print("\nTraining features:", X_train_model.shape)
print("Validation features:", X_val_model.shape)

print("\nCategorical features:")
print(categorical_columns)

print("\nNumerical features:")
print([
    column for column in X_train_model.columns
    if column not in categorical_columns
])

# Install CatBoost for the modeling stage
!pip install catboost -q

# Train the first CatBoost baseline model.
# CatBoost is suitable here because it can handle categorical
# features directly without one-hot encoding.

from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Convert categorical columns to strings.
# This ensures CatBoost treats them correctly.
for col in categorical_columns:
    X_train_model[col] = X_train_model[col].astype(str)
    X_val_model[col] = X_val_model[col].astype(str)

# Find categorical column positions.
cat_feature_indices = [
    X_train_model.columns.get_loc(col)
    for col in categorical_columns
]

# Create the baseline CatBoost model.
catboost_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    eval_metric="RMSE",
    random_seed=42,
    verbose=100
)

print("TRAINING CATBOOST MODEL")
print("=" * 60)

# Train using the time-based validation set for evaluation.
catboost_model.fit(
    X_train_model,
    y_train_model,
    cat_features=cat_feature_indices,
    eval_set=(X_val_model, y_val_model),
    early_stopping_rounds=100
)

print("\nModel training completed.")
print("Best iteration:", catboost_model.get_best_iteration())

# Evaluate CatBoost baseline on the time-based validation set.

y_val_pred = catboost_model.predict(X_val_model)

mae = mean_absolute_error(y_val_model, y_val_pred)
rmse = np.sqrt(mean_squared_error(y_val_model, y_val_pred))
r2 = r2_score(y_val_model, y_val_pred)

print("CATBOOST BASELINE VALIDATION RESULTS")
print("=" * 60)

print(f"MAE  : {mae:,.2f}")
print(f"RMSE : {rmse:,.2f}")
print(f"R²   : {r2:.4f}")

# Analyze validation prediction errors.
# This helps us understand where the baseline model performs poorly.

validation_results = validation_features[
    ["load_id", "pickup", "delivery", "equipment", "distance", "weight", "date", "posted_rate"]
].copy()

validation_results["predicted_rate"] = y_val_pred

validation_results["error"] = (
    validation_results["posted_rate"]
    - validation_results["predicted_rate"]
)

validation_results["absolute_error"] = (
    validation_results["error"].abs()
)

validation_results["percentage_error"] = (
    validation_results["absolute_error"]
    / validation_results["posted_rate"].replace(0, np.nan)
) * 100

print("PREDICTION ERROR ANALYSIS")
print("=" * 60)

print("\nError statistics:")
print(validation_results["error"].describe())

print("\nAbsolute error statistics:")
print(validation_results["absolute_error"].describe())

print("\nMean absolute percentage error:")
print(
    validation_results["percentage_error"].mean()
)

print("\nLargest prediction errors:")
display(
    validation_results
    .sort_values("absolute_error", ascending=False)
    .head(10)
)

# Visualize actual vs predicted posted rates.
# This helps identify systematic prediction errors and extreme outliers.

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

plt.scatter(
    validation_results["posted_rate"],
    validation_results["predicted_rate"],
    alpha=0.35
)

# Perfect-prediction reference line
max_value = max(
    validation_results["posted_rate"].max(),
    validation_results["predicted_rate"].max()
)

plt.plot(
    [0, max_value],
    [0, max_value],
    linestyle="--",
    linewidth=2
)

plt.xlabel("Actual Posted Rate ($)")
plt.ylabel("Predicted Posted Rate ($)")
plt.title("Actual vs Predicted Posted Freight Rate")

plt.xlim(0, max_value)
plt.ylim(0, max_value)

plt.grid(alpha=0.2)
plt.tight_layout()
plt.show()

# Examine prediction error across different posted-rate ranges.

validation_results["rate_group"] = pd.cut(
    validation_results["posted_rate"],
    bins=[0, 1000, 2000, 3000, 5000, 10000, np.inf],
    labels=[
        "0–1K",
        "1K–2K",
        "2K–3K",
        "3K–5K",
        "5K–10K",
        "10K+"
    ],
    include_lowest=True
)

error_by_group = (
    validation_results
    .groupby("rate_group", observed=True)
    .agg(
        count=("posted_rate", "size"),
        mean_actual=("posted_rate", "mean"),
        mean_absolute_error=("absolute_error", "mean"),
        median_absolute_error=("absolute_error", "median")
    )
)

print("ERROR BY POSTED-RATE RANGE")
print("=" * 70)

display(error_by_group)

# ============================================================
# CATBOOST FEATURE IMPORTANCE
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# Get feature names directly from the trained CatBoost model
feature_names = catboost_model.feature_names_
feature_importance = catboost_model.get_feature_importance()

# Check lengths
print("Number of feature names:", len(feature_names))
print("Number of importance values:", len(feature_importance))

# Create DataFrame
importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": feature_importance
})

# Sort from most to least important
importance_df = importance_df.sort_values(
    "importance",
    ascending=False
).reset_index(drop=True)

print("\nCATBOOST FEATURE IMPORTANCE")
print("=" * 60)
print(importance_df.to_string(index=False))

# ============================================================
# PLOT TOP 15 FEATURES
# ============================================================

top_n = min(15, len(importance_df))

top_features = (
    importance_df
    .head(top_n)
    .sort_values("importance")
)

plt.figure(figsize=(7, 4))

plt.barh(
    top_features["feature"],
    top_features["importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 15 CatBoost Feature Importances")
plt.tight_layout()
plt.show()

# Check the variables currently available

print("Variables related to validation/prediction:")

for name in sorted(dir()):
    if any(x in name.lower() for x in ["valid", "pred", "target", "catboost"]):
        print(name)

# ============================================================
# RESIDUAL ANALYSIS
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Actual target values
y_val_actual = model_validation[target].values

# Create residual dataframe
residual_df = pd.DataFrame({
    "actual": y_val_actual,
    "predicted": y_val_pred
})

# Calculate errors
residual_df["error"] = (
    residual_df["actual"] - residual_df["predicted"]
)

residual_df["absolute_error"] = (
    residual_df["error"].abs()
)

# Add important features
residual_df["distance"] = validation_features["distance"].values
residual_df["weight"] = validation_features["weight"].values

# ============================================================
# ERROR STATISTICS
# ============================================================

print("RESIDUAL ANALYSIS")
print("=" * 60)

print("\nError statistics:")
print(residual_df["error"].describe())

print("\nAbsolute error statistics:")
print(residual_df["absolute_error"].describe())

# ============================================================
# ERROR BY DISTANCE RANGE
# ============================================================

residual_df["distance_group"] = pd.cut(
    residual_df["distance"],
    bins=[0, 500, 1000, 1500, 2000, 3000, np.inf],
    labels=[
        "0-500",
        "500-1K",
        "1K-1.5K",
        "1.5K-2K",
        "2K-3K",
        "3K+"
    ]
)

distance_error = residual_df.groupby(
    "distance_group",
    observed=True
).agg(
    count=("absolute_error", "size"),
    mean_absolute_error=("absolute_error", "mean"),
    median_absolute_error=("absolute_error", "median")
)

print("\nERROR BY DISTANCE RANGE")
print("=" * 60)
print(distance_error)

# ============================================================
# RESIDUAL PLOT
# ============================================================

plt.figure(figsize=(10, 6))

plt.scatter(
    residual_df["actual"],
    residual_df["error"],
    alpha=0.4
)

plt.axhline(
    y=0,
    linestyle="--"
)

plt.xlabel("Actual Posted Rate ($)")
plt.ylabel("Prediction Error ($)")
plt.title("Residuals vs Actual Posted Rate")

plt.tight_layout()
plt.show()

# ============================================================
# HIGH-RATE ERROR ANALYSIS
# ============================================================

# Add actual and predicted rate information
high_rate_analysis = residual_df.copy()

# Calculate percentage error
high_rate_analysis["percentage_error"] = (
    high_rate_analysis["absolute_error"]
    / high_rate_analysis["actual"].abs()
) * 100

# Select high actual-rate records
high_rate = high_rate_analysis[
    high_rate_analysis["actual"] >= 10000
].copy()

print("HIGH-RATE RECORDS (ACTUAL RATE >= $10,000)")
print("=" * 70)

print(f"Number of records: {len(high_rate)}")

if len(high_rate) > 0:

    print("\nError statistics:")
    print(high_rate[
        ["actual", "predicted", "error", "absolute_error", "percentage_error"]
    ].describe())

    print("\nSample of high-rate records:")

    # Show the largest errors
    largest_high_rate_errors = high_rate.sort_values(
        "absolute_error",
        ascending=False
    ).head(20)

    display(largest_high_rate_errors)

else:
    print("No records with actual rate >= $10,000.")

# ============================================================
# HIGH-RATE PATTERN ANALYSIS
# ============================================================

print("=" * 70)
print("HIGH-RATE PATTERN ANALYSIS")
print("=" * 70)

# Select high-rate records
high_rate = validation_results[
    validation_results["posted_rate"] >= 10000
].copy()

print(f"\nNumber of high-rate records: {len(high_rate)}")

# ------------------------------------------------------------
# Create distance groups directly
# ------------------------------------------------------------

bins = [0, 500, 1000, 1500, 2000, 3000, float("inf")]
labels = ["0-500", "500-1K", "1K-1.5K", "1.5K-2K", "2K-3K", "3K+"]

high_rate["distance_group"] = pd.cut(
    high_rate["distance"],
    bins=bins,
    labels=labels,
    right=False
)

# ------------------------------------------------------------
# Feature statistics
# ------------------------------------------------------------

print("\nHigh-rate feature statistics:")

print(
    high_rate[
        ["posted_rate", "predicted_rate", "distance", "weight"]
    ].describe().round(2)
)

# ------------------------------------------------------------
# Average values
# ------------------------------------------------------------

print("\nHigh-rate averages:")

print(f"Actual rate:    ${high_rate['posted_rate'].mean():,.2f}")
print(f"Predicted rate: ${high_rate['predicted_rate'].mean():,.2f}")
print(f"Distance:       {high_rate['distance'].mean():,.2f}")
print(f"Weight:         {high_rate['weight'].mean():,.2f}")

# ------------------------------------------------------------
# Equipment distribution
# ------------------------------------------------------------

print("\nEquipment distribution among high-rate records:")
print(high_rate["equipment"].value_counts())

# ------------------------------------------------------------
# Distance groups
# ------------------------------------------------------------

print("\nDistance groups among high-rate records:")
print(high_rate["distance_group"].value_counts().sort_index())

# ------------------------------------------------------------
# Show records
# ------------------------------------------------------------

print("\nHigh-rate records:")

display(
    high_rate[
        [
            "load_id",
            "pickup",
            "delivery",
            "equipment",
            "distance",
            "weight",
            "posted_rate",
            "predicted_rate",
            "error",
            "absolute_error",
            "percentage_error",
            "distance_group"
        ]
    ].sort_values(
        "posted_rate",
        ascending=False
    )
)

# ==========================================
# IMPROVED CATBOOST MODEL - LOG TARGET
# ==========================================

from catboost import CatBoostRegressor
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("TRAINING IMPROVED CATBOOST MODEL")
print("=" * 60)

# Define categorical features explicitly
categorical_features = ['pickup', 'delivery', 'equipment', 'route']

# Log-transform the target
y_train_log = np.log1p(y_train)

# Train improved CatBoost model
improved_catboost_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.03,
    depth=8,
    loss_function='RMSE',
    eval_metric='RMSE',
    random_seed=42,
    verbose=100,
    early_stopping_rounds=100
)

improved_catboost_model.fit(
    X_train,
    y_train_log,
    cat_features=categorical_features,
    eval_set=(X_validation, np.log1p(y_validation)),
    verbose=100
)

# Predict in log scale
y_pred_log = improved_catboost_model.predict(X_validation)

# Convert predictions back to original dollar scale
y_pred_improved = np.expm1(y_pred_log)

# Prevent negative predictions
y_pred_improved = np.maximum(y_pred_improved, 0)

# Calculate metrics
mae_log = mean_absolute_error(y_validation, y_pred_improved)
rmse_log = np.sqrt(mean_squared_error(y_validation, y_pred_improved))
r2_log = r2_score(y_validation, y_pred_improved)

print("\nIMPROVED CATBOOST VALIDATION RESULTS")
print("=" * 60)
print(f"MAE : {mae_log:.2f}")
print(f"RMSE: {rmse_log:.2f}")
print(f"R²  : {r2_log:.4f}")

print("Validation-related variables and their columns:")
print("=" * 70)

for name in [
    'validation',
    'validation_clean',
    'validation_features',
    'validation_missing',
    'validation_negative',
    'validation_zero'
]:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, 'columns'):
            print(f"\n{name}:")
            print(obj.shape)
            print(obj.columns.tolist())

# ============================================================
# PREPARE VALIDATION DATA FOR FINAL 18-FEATURE MODEL
# ============================================================

validation_final = validation_clean.copy()

# Missing values — same approach as training
validation_final['weight'] = validation_final['weight'].fillna(
    X_train['weight'].median()
)

validation_final['market_index'] = validation_final['market_index'].fillna(
    X_train['market_index'].median()
)

# Date features
validation_final['date'] = pd.to_datetime(validation_final['date'])

validation_final['year'] = validation_final['date'].dt.year
validation_final['month'] = validation_final['date'].dt.month
validation_final['day'] = validation_final['date'].dt.day
validation_final['day_of_week'] = validation_final['date'].dt.dayofweek
validation_final['day_of_year'] = validation_final['date'].dt.dayofyear
validation_final['week_of_year'] = (
    validation_final['date'].dt.isocalendar().week.astype(int)
)

# Route
validation_final['route'] = (
    validation_final['pickup'].astype(str)
    + ' -> '
    + validation_final['delivery'].astype(str)
)

# EXACTLY the 18 features used by final_candidate_model
X_validation_final = validation_final[original_features].copy()

print("Final validation shape:", X_validation_final.shape)
print("Feature count:", len(X_validation_final.columns))
print("Features:")
print(X_validation_final.columns.tolist())

print("\nRemaining missing values:")
print(X_validation_final.isna().sum())

# ============================================================
# FINAL PREDICTIONS — SELECTED 18-FEATURE CATBOOST MODEL
# ============================================================

print("Generating final predictions...")

final_predictions = final_candidate_model.predict(
    X_validation_final
)

print("Prediction completed!")
print("Prediction shape:", final_predictions.shape)

print("\nFirst 10 predictions:")
print(final_predictions[:10])

print("\nPrediction statistics:")
print(pd.Series(final_predictions).describe())

# ============================================================
# CREATE FINAL VALIDATION PREDICTIONS FILE
# ============================================================

submission = pd.DataFrame({
    "load_id": validation_clean["load_id"].values,
    "predicted_rate": final_predictions
})

submission.to_csv(
    "validation_predictions.csv",
    index=False
)

print("FINAL SUBMISSION CREATED")
print("=" * 60)
print("Filename: validation_predictions.csv")
print("Shape:", submission.shape)

print("\nColumns:")
print(submission.columns.tolist())

print("\nMissing values:")
print(submission.isna().sum())

print("\nDuplicate load IDs:")
print(submission["load_id"].duplicated().sum())

print("\nFirst 10 rows:")
display(submission.head(10))

eval_set=(X_validation, np.log1p(y_validation))

# Identify categorical features automatically
categorical_features = X_train.select_dtypes(
    include=['object', 'category']
).columns.tolist()

print("Categorical features:")
print(categorical_features)
print("\nNumber of categorical features:", len(categorical_features))

print("X_train columns:")
print(X_train.columns.tolist())

print("\nCategorical features:")
print(categorical_features)

print("\nMissing categorical features:")
print([col for col in categorical_features if col not in X_train.columns])

print("X_train dtypes:")
print(X_train.dtypes)

print("\nNon-numeric values in numerical columns:")

numeric_columns = [
    'pickup_lat',
    'pickup_lon',
    'delivery_lat',
    'delivery_lon',
    'distance',
    'weight',
    'market_index',
    'quote_signal'
]

for col in numeric_columns:
    bad_values = pd.to_numeric(X_train[col], errors='coerce').isna().sum()

    if bad_values > 0:
        print(f"{col}: {bad_values} invalid values")
        print(X_train.loc[
            pd.to_numeric(X_train[col], errors='coerce').isna(),
            col
        ].head())

# Fill missing numerical values using training-set medians

numeric_columns = [
    'pickup_lat',
    'pickup_lon',
    'delivery_lat',
    'delivery_lon',
    'distance',
    'weight',
    'market_index',
    'quote_signal'
]

for col in numeric_columns:
    median_value = X_train[col].median()

    X_train[col] = X_train[col].fillna(median_value)
    X_validation[col] = X_validation[col].fillna(median_value)

print("Remaining missing values in X_train:")
print(X_train[numeric_columns].isna().sum())

print("\nRemaining missing values in X_validation:")
print(X_validation[numeric_columns].isna().sum())

print("X_train shape:", X_train.shape)

print("\nX_train columns:")
print(X_train.columns.tolist())

print("\nFirst 3 rows:")
print(X_train.head(3))

print("\nFirst 3 rows as values:")
print(X_train.iloc[:3, :].values)

print("\nColumn-by-column first value:")
for i, col in enumerate(X_train.columns):
    print(i, col, "=>", repr(X_train.iloc[0, i]))

# ============================================================
# FRESH CATBOOST MODEL - LOG TARGET
# ============================================================

from catboost import CatBoostRegressor
import numpy as np

# Correctly assign the prepared training and validation data
X_train = X_train_model.copy()
y_train = y_train_model.copy()
X_validation = X_val_model.copy()
y_validation = y_val_model.copy()

# Categorical columns that actually exist in X_train (including engineered 'route')
categorical_features_valid = [
    'pickup',
    'delivery',
    'equipment',
    'route' # Add 'route' as it's an engineered categorical feature
]

# Convert column names to column indices
categorical_indices = [
    X_train.columns.get_loc(col)
    for col in categorical_features_valid
]

print("Categorical columns:", categorical_features_valid)
print("Categorical indices:", categorical_indices)

# Log-transform the target (ensure this is done after y_train is set)
y_train_log = np.log1p(y_train)

# Create a completely new model
log_catboost_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function='RMSE',
    eval_metric='RMSE',
    random_seed=42,
    verbose=100,
    allow_writing_files=False
)

print("\nStarting training...")

# Define eval_set using the corrected X_validation and y_validation
eval_set_corrected = (X_validation, np.log1p(y_validation))

log_catboost_model.fit(
    X_train,
    y_train_log,
    cat_features=categorical_indices,
    eval_set=eval_set_corrected,
    verbose=100
)

print("\nTraining completed successfully.")
print("Best iteration:", log_catboost_model.get_best_iteration())

# Predict in log scale
y_pred_log = log_catboost_model.predict(X_validation)

# Convert predictions back to original dollar scale
y_pred_improved = np.expm1(y_pred_log)

# Prevent negative predictions
y_pred_improved = np.maximum(y_pred_improved, 0)

# Calculate metrics (assuming these are defined elsewhere or will be defined next)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae_log = mean_absolute_error(y_validation, y_pred_improved)
rmse_log = np.sqrt(mean_squared_error(y_validation, y_pred_improved))
r2_log = r2_score(y_validation, y_pred_improved)

print("\nIMPROVED CATBOOST VALIDATION RESULTS")
print("=" * 60)
print(f"MAE : {mae_log:.2f}")
print(f"RMSE: {rmse_log:.2f}")
print(f"R²  : {r2_log:.4f}")

# ============================================================
# FINAL FEATURE INVENTORY
# ============================================================

print("CURRENT MODEL FEATURES")
print("=" * 60)

for i, column in enumerate(X_train.columns, start=1):
    print(f"{i:2}. {column}")

print("\nNumber of features:", X_train.shape[1])
print("Training rows:", X_train.shape[0])
print("Validation rows:", X_validation.shape[0])

# ============================================================
# ADDITIONAL FEATURE ENGINEERING
# ============================================================

def add_freight_features(df):
    df = df.copy()

    # Avoid division by zero
    safe_distance = df["distance"].replace(0, np.nan)

    # Weight relative to shipment distance
    df["weight_per_mile"] = (
        df["weight"] / safe_distance
    )

    # Non-linear distance effect
    df["distance_squared"] = (
        df["distance"] ** 2
    )

    # Interaction between shipment weight and distance
    df["weight_distance_interaction"] = (
        df["weight"] * df["distance"]
    )

    # Geographic differences between origin and destination
    df["latitude_difference"] = (
        df["delivery_lat"] - df["pickup_lat"]
    ).abs()

    df["longitude_difference"] = (
        df["delivery_lon"] - df["pickup_lon"]
    ).abs()

    # Replace any infinite/missing values created by division
    df["weight_per_mile"] = (
        df["weight_per_mile"]
        .replace([np.inf, -np.inf], np.nan)
    )

    return df


# Apply to training and validation features
X_train_engineered = add_freight_features(X_train)
X_validation_engineered = add_freight_features(X_validation)

# Use training medians for any newly created missing values
new_numeric_features = [
    "weight_per_mile",
    "distance_squared",
    "weight_distance_interaction",
    "latitude_difference",
    "longitude_difference"
]

for col in new_numeric_features:
    median_value = X_train_engineered[col].median()

    X_train_engineered[col] = (
        X_train_engineered[col].fillna(median_value)
    )

    X_validation_engineered[col] = (
        X_validation_engineered[col].fillna(median_value)
    )

print("Original feature count:", X_train.shape[1])
print("Engineered feature count:", X_train_engineered.shape[1])

print("\nNew features:")
for feature in new_numeric_features:
    print("-", feature)

# Check the engineered features

print(
    X_train_engineered[
        new_numeric_features
    ].describe().round(2)
)

# ============================================================
# CHECK NEGATIVE VALUES IN ENGINEERED FEATURES
# ============================================================

print("Negative distance values:")
print((X_train_engineered["distance"] < 0).sum())

print("\nNegative weight values:")
print((X_train_engineered["weight"] < 0).sum())

print("\nRows with negative distance:")
display(
    X_train_engineered[
        X_train_engineered["distance"] < 0
    ][
        [
            "pickup",
            "delivery",
            "distance",
            "weight",
            "equipment",
            "market_index",
            "quote_signal"
        ]
    ].head(20)
)

print("\nRows with negative weight:")
display(
    X_train_engineered[
        X_train_engineered["weight"] < 0
    ][
        [
            "pickup",
            "delivery",
            "distance",
            "weight",
            "equipment",
            "market_index",
            "quote_signal"
        ]
    ].head(20)
)

# ============================================================
# CLEAN WEIGHT-BASED ENGINEERED FEATURES
# ============================================================

# Create a valid weight copy for feature engineering.
# Negative weights are treated as invalid observations.
valid_weight = X_train_engineered["weight"].where(
    X_train_engineered["weight"] >= 0,
    np.nan
)

valid_weight_validation = X_validation_engineered["weight"].where(
    X_validation_engineered["weight"] >= 0,
    np.nan
)

# Weight per mile
X_train_engineered["weight_per_mile"] = (
    valid_weight / X_train_engineered["distance"]
)

X_validation_engineered["weight_per_mile"] = (
    valid_weight_validation / X_validation_engineered["distance"]
)

# Weight-distance interaction
X_train_engineered["weight_distance_interaction"] = (
    valid_weight * X_train_engineered["distance"]
)

X_validation_engineered["weight_distance_interaction"] = (
    valid_weight_validation * X_validation_engineered["distance"]
)

# Use training medians to fill invalid/missing engineered values
for column in [
    "weight_per_mile",
    "weight_distance_interaction"
]:
    median_value = X_train_engineered[column].median()

    X_train_engineered[column] = (
        X_train_engineered[column].fillna(median_value)
    )

    X_validation_engineered[column] = (
        X_validation_engineered[column].fillna(median_value)
    )

print("Engineered feature check:")
print(
    X_train_engineered[
        [
            "weight_per_mile",
            "distance_squared",
            "weight_distance_interaction",
            "latitude_difference",
            "longitude_difference"
        ]
    ].describe().round(2)
)

# ============================================================
# CATBOOST WITH ENGINEERED FEATURES
# ============================================================

# Identify categorical columns that actually exist
engineered_categorical_features = [
    col
    for col in ["pickup", "delivery", "equipment", "route"]
    if col in X_train_engineered.columns
]

engineered_categorical_indices = [
    X_train_engineered.columns.get_loc(col)
    for col in engineered_categorical_features
]

print("Categorical features:", engineered_categorical_features)
print("Categorical indices:", engineered_categorical_indices)

# Create a fresh CatBoost model
engineered_catboost_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    eval_metric="RMSE",
    random_seed=42,
    verbose=100,
    allow_writing_files=False
)

print("\nStarting training...")

engineered_catboost_model.fit(
    X_train_engineered,
    y_train,
    cat_features=engineered_categorical_indices,
    eval_set=(X_validation_engineered, y_validation),
    verbose=100
)

print("\nTraining completed.")
print(
    "Best iteration:",
    engineered_catboost_model.get_best_iteration()
)

# ============================================================
# EVALUATE ENGINEERED-FEATURE MODEL
# ============================================================

y_pred_engineered = engineered_catboost_model.predict(
    X_validation_engineered
)

mae_engineered = mean_absolute_error(
    y_validation,
    y_pred_engineered
)

rmse_engineered = np.sqrt(
    mean_squared_error(
        y_validation,
        y_pred_engineered
    )
)

r2_engineered = r2_score(
    y_validation,
    y_pred_engineered
)

print("ENGINEERED CATBOOST VALIDATION RESULTS")
print("=" * 60)
print(f"MAE : ${mae_engineered:,.2f}")
print(f"RMSE: ${rmse_engineered:,.2f}")
print(f"R²  : {r2_engineered:.4f}")

# ============================================================
# FINAL CANDIDATE ERROR ANALYSIS
# ============================================================

# Use the predictions from the engineered CatBoost model
baseline_predictions = engineered_catboost_model.predict(X_validation_engineered)

error_analysis = validation_features.copy()

error_analysis["actual_rate"] = y_validation.values
error_analysis["predicted_rate"] = baseline_predictions

error_analysis["error"] = (
    error_analysis["actual_rate"]
    - error_analysis["predicted_rate"]
)

error_analysis["absolute_error"] = (
    error_analysis["error"].abs()
)

error_analysis["squared_error"] = (
    error_analysis["error"] ** 2
)

print("ERROR ANALYSIS")
print("=" * 60)

print(f"MAE : ${error_analysis['absolute_error'].mean():,.2f}")
print(
    f"RMSE: ${np.sqrt(error_analysis['squared_error'].mean()):,.2f}"
)

print("\nLargest absolute errors:")
display(
    error_analysis[
        [
            "actual_rate",
            "predicted_rate",
            "error",
            "absolute_error"
        ]
    ]
    .sort_values("absolute_error", ascending=False)
    .head(20)
)

# ============================================================
# HIGH-RATE ERROR ANALYSIS
# ============================================================

# Combine actual rates, predictions and original features
high_rate_analysis = validation_features.copy()

high_rate_analysis["actual_rate"] = y_validation.values
high_rate_analysis["predicted_rate"] = baseline_predictions
high_rate_analysis["absolute_error"] = (
    high_rate_analysis["actual_rate"]
    - high_rate_analysis["predicted_rate"]
).abs()

# Identify high-rate loads
high_rate = high_rate_analysis[
    high_rate_analysis["actual_rate"] >= 10000
].copy()

print("HIGH-RATE LOAD ANALYSIS")
print("=" * 60)

print("Number of loads with actual rate >= $10,000:", len(high_rate))

print("\nAverage actual rate:")
print(f"${high_rate['actual_rate'].mean():,.2f}")

print("\nAverage predicted rate:")
print(f"${high_rate['predicted_rate'].mean():,.2f}")

print("\nAverage absolute error:")
print(f"${high_rate['absolute_error'].mean():,.2f}")

print("\nHigh-rate loads by equipment:")
display(
    high_rate["equipment"]
    .value_counts()
)

print("\nHigh-rate loads by month:")
display(
    high_rate["month"]
    .value_counts()
    .sort_index()
)

print("\nHigh-rate load features:")
display(
    high_rate[
        [
            "pickup",
            "delivery",
            "distance",
            "equipment",
            "weight",
            "market_index",
            "quote_signal",
            "month",
            "actual_rate",
            "predicted_rate",
            "absolute_error"
        ]
    ]
    .sort_values("actual_rate", ascending=False)
    .head(20)
)

# ============================================================
# VALIDATION PERFORMANCE BY MONTH
# ============================================================

monthly_results = error_analysis.groupby("month").agg(
    observations=("actual_rate", "size"),
    mean_actual_rate=("actual_rate", "mean"),
    mean_predicted_rate=("predicted_rate", "mean"),
    mae=("absolute_error", "mean"),
    rmse=("error", lambda x: np.sqrt(np.mean(x ** 2)))
).reset_index()

monthly_results["mean_error"] = (
    monthly_results["mean_actual_rate"]
    - monthly_results["mean_predicted_rate"]
)

display(
    monthly_results.round(2)
)

# ============================================================
# CHECK FINAL CANDIDATE MODEL
# ============================================================

print("Final candidate model:")
print(type(engineered_catboost_model))

print("\nNumber of features:")
print(len(X_train_engineered.columns))

print("\nFeatures:")
print(X_train_engineered.columns.tolist())

print("\nBest iteration:")
print(engineered_catboost_model.get_best_iteration())

# ============================================================
# CHECK ALL MODEL VARIABLES
# ============================================================

print("Available model objects:")
print("=" * 60)

for name in [
    "baseline_model",
    "catboost_model",
    "improved_catboost_model",
    "log_catboost_model",
    "engineered_catboost_model"
]:
    if name in globals():
        model = globals()[name]

        print(f"\n{name}")
        print("-" * 40)
        print("Type:", type(model).__name__)

        if hasattr(model, "get_best_iteration"):
            print("Best iteration:", model.get_best_iteration())

# ============================================================
# IDENTIFY THE ORIGINAL BASELINE MODEL
# ============================================================

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

models_to_check = {
    "catboost_model": catboost_model,
    "improved_catboost_model": improved_catboost_model
}

for model_name, model in models_to_check.items():

    print("\n" + "=" * 60)
    print(model_name)
    print("=" * 60)

    try:
        predictions = model.predict(X_validation)

        mae = mean_absolute_error(
            y_validation,
            predictions
        )

        rmse = np.sqrt(
            mean_squared_error(
                y_validation,
                predictions
            )
        )

        r2 = r2_score(
            y_validation,
            predictions
        )

        print(f"MAE : ${mae:,.2f}")
        print(f"RMSE: ${rmse:,.2f}")
        print(f"R²  : {r2:.4f}")

    except Exception as e:
        print("ERROR:", e)

# ============================================================
# FINAL BASELINE CATBOOST MODEL
# 18 ORIGINAL FEATURES ONLY
# ============================================================

# Original feature columns
original_features = [
    'pickup',
    'delivery',
    'pickup_lat',
    'pickup_lon',
    'delivery_lat',
    'delivery_lon',
    'distance',
    'equipment',
    'weight',
    'market_index',
    'quote_signal',
    'year',
    'month',
    'day',
    'day_of_week',
    'day_of_year',
    'week_of_year',
    'route'
]

# Create clean copies containing ONLY the original features
X_train_final = X_train[original_features].copy()
X_validation_final = X_validation[original_features].copy()

# Categorical features
final_categorical_features = [
    'pickup',
    'delivery',
    'equipment',
    'route'
]

final_categorical_indices = [
    X_train_final.columns.get_loc(col)
    for col in final_categorical_features
]

print("Final feature count:", len(original_features))
print("Final features:", original_features)
print("Categorical features:", final_categorical_features)

# Fresh model
final_candidate_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function='RMSE',
    eval_metric='RMSE',
    random_seed=42,
    verbose=100,
    allow_writing_files=False
)

# Train
final_candidate_model.fit(
    X_train_final,
    y_train,
    cat_features=final_categorical_indices,
    eval_set=(X_validation_final, y_validation),
    verbose=100
)

print("\nFinal candidate training completed.")
print(
    "Best iteration:",
    final_candidate_model.get_best_iteration()
)

# ============================================================
# FINAL CANDIDATE VALIDATION
# ============================================================

final_validation_predictions = (
    final_candidate_model.predict(X_validation_final)
)

final_mae = mean_absolute_error(
    y_validation,
    final_validation_predictions
)

final_rmse = np.sqrt(
    mean_squared_error(
        y_validation,
        final_validation_predictions
    )
)

final_r2 = r2_score(
    y_validation,
    final_validation_predictions
)

print("FINAL CANDIDATE VALIDATION RESULTS")
print("=" * 60)
print(f"MAE : ${final_mae:,.2f}")
print(f"RMSE: ${final_rmse:,.2f}")
print(f"R²  : {final_r2:.4f}")

# ============================================================
# CREATE VALIDATION PREDICTIONS
# ============================================================

validation_predictions_df = X_validation_final.copy()

# Add actual and predicted freight rates
validation_predictions_df["actual_rate"] = y_validation.values
validation_predictions_df["predicted_rate"] = (
    final_validation_predictions
)

# Calculate prediction error
validation_predictions_df["error"] = (
    validation_predictions_df["actual_rate"]
    - validation_predictions_df["predicted_rate"]
)

validation_predictions_df["absolute_error"] = (
    validation_predictions_df["error"].abs()
)

print("Validation predictions shape:")
print(validation_predictions_df.shape)

print("\nFirst 5 predictions:")
display(
    validation_predictions_df[
        [
            "actual_rate",
            "predicted_rate",
            "error",
            "absolute_error"
        ]
    ].head()
)

print("Validation dataset shape:", validation_clean.shape)
print("\nValidation columns:")
print(validation_clean.columns.tolist())

print("\nFirst 5 rows:")
display(validation_clean.head())

print("\nMissing values:")
print(validation_clean.isna().sum())

# ============================================================
# PREPARE VALIDATION DATA FOR FINAL MODEL
# ============================================================

validation_final = validation_clean.copy()

# ------------------------------------------------------------
# 1. Handle missing numerical values
#    Use the same approach as training
# ------------------------------------------------------------

validation_final['weight'] = validation_final['weight'].fillna(
    X_train['weight'].median()
)

validation_final['market_index'] = validation_final['market_index'].fillna(
    X_train['market_index'].median()
)

# ------------------------------------------------------------
# 2. Date features
# ------------------------------------------------------------

validation_final['date'] = pd.to_datetime(validation_final['date'])

validation_final['year'] = validation_final['date'].dt.year
validation_final['month'] = validation_final['date'].dt.month
validation_final['day'] = validation_final['date'].dt.day
validation_final['day_of_week'] = validation_final['date'].dt.dayofweek
validation_final['day_of_year'] = validation_final['date'].dt.dayofyear
validation_final['week_of_year'] = validation_final['date'].dt.isocalendar().week.astype(int)

# ------------------------------------------------------------
# 3. Route feature
# ------------------------------------------------------------

validation_final['route'] = (
    validation_final['pickup'].astype(str)
    + ' -> '
    + validation_final['delivery'].astype(str)
)

# ------------------------------------------------------------
# 4. Engineered numerical features
# ------------------------------------------------------------

validation_final['weight_per_mile'] = (
    validation_final['weight'] /
    validation_final['distance'].replace(0, np.nan)
)

validation_final['weight_per_mile'] = validation_final['weight_per_mile'].fillna(0)

validation_final['distance_squared'] = (
    validation_final['distance'] ** 2
)

validation_final['weight_distance_interaction'] = (
    validation_final['weight'] *
    validation_final['distance']
)

validation_final['latitude_difference'] = (
    abs(validation_final['pickup_lat'] -
        validation_final['delivery_lat'])
)

validation_final['longitude_difference'] = (
    abs(validation_final['pickup_lon'] -
        validation_final['delivery_lon'])
)

# ------------------------------------------------------------
# 5. Select EXACTLY the 23 model features
# ------------------------------------------------------------

final_features = [
    'pickup',
    'delivery',
    'pickup_lat',
    'pickup_lon',
    'delivery_lat',
    'delivery_lon',
    'distance',
    'equipment',
    'weight',
    'market_index',
    'quote_signal',
    'year',
    'month',
    'day',
    'day_of_week',
    'day_of_year',
    'week_of_year',
    'route',
    'weight_per_mile',
    'distance_squared',
    'weight_distance_interaction',
    'latitude_difference',
    'longitude_difference'
]

X_validation_final = validation_final[final_features].copy()

print("Final validation shape:", X_validation_final.shape)
print("\nFeature count:", len(X_validation_final.columns))
print("\nFeatures:")
print(X_validation_final.columns.tolist())

print("\nRemaining missing values:")
print(X_validation_final.isna().sum())

# ============================================================
# FINAL PREDICTIONS
# ============================================================

print("Generating final predictions...")

# Predict using the final trained model
final_predictions = engineered_catboost_model.predict(X_validation_final)

print("Prediction completed!")
print("Prediction shape:", final_predictions.shape)

print("\nFirst 10 predictions:")
print(final_predictions[:10])

print("\nPrediction statistics:")
print(pd.Series(final_predictions).describe())

# ============================================================
# CREATE FINAL SUBMISSION FILE
# ============================================================

submission = pd.DataFrame({
    'load_id': validation_clean['load_id'].values,
    'predicted_rate': final_predictions
})

# Save CSV
submission.to_csv('submission.csv', index=False)

print("Submission created successfully!")
print("Shape:", submission.shape)

print("\nFirst 10 rows:")
display(submission.head(10))

print("\nColumns:")
print(submission.columns.tolist())

print("\nMissing values:")
print(submission.isna().sum())

print("\nFile saved as: submission.csv")

from google.colab import files
files.download('/content/submission.csv')

submission.to_csv(
    'validation_predictions.csv',
    index=False
)

print("Saved validation_predictions.csv")
print("Rows:", len(submission))
print("Columns:", submission.columns.tolist())

# ============================================================
# VISUALIZATION 1 — ACTUAL FREIGHT RATE DISTRIBUTION
# ============================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.hist(
    y_validation,
    bins=50
)

plt.xlabel("Actual Freight Rate ($)")
plt.ylabel("Number of Loads")
plt.title("Distribution of Actual Freight Rates")

plt.tight_layout()
plt.show()

# VISUALIZATION 2 — ACTUAL VS PREDICTED FREIGHT RATE


import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(10, 7))

plt.scatter(
    y_validation,
    final_validation_predictions,
    alpha=0.35,
    s=18
)

# Perfect prediction line
min_value = min(y_validation.min(), final_validation_predictions.min())
max_value = max(y_validation.max(), final_validation_predictions.max())

plt.plot(
    [min_value, max_value],
    [min_value, max_value],
    linestyle='--',
    linewidth=2
)

plt.xlabel("Actual Freight Rate ($)")
plt.ylabel("Predicted Freight Rate ($)")
plt.title("Actual vs Predicted Freight Rates")

plt.tight_layout()
plt.show()

# ============================================================
# VISUALIZATION 3 — RESIDUAL / ERROR DISTRIBUTION
# ============================================================

errors = (
    y_validation.values
    - final_validation_predictions
)

plt.figure(figsize=(10, 6))

plt.hist(
    errors,
    bins=50
)

plt.axvline(
    0,
    linestyle='--',
    linewidth=2
)

plt.xlabel("Prediction Error ($)")
plt.ylabel("Number of Loads")
plt.title("Distribution of Prediction Errors")

plt.tight_layout()
plt.show()

# ============================================================
# VISUALIZATION 4 — ABSOLUTE ERROR VS ACTUAL RATE
# ============================================================

absolute_errors = np.abs(
    y_validation.values - final_validation_predictions
)

plt.figure(figsize=(10, 7))

plt.scatter(
    y_validation,
    absolute_errors,
    alpha=0.35,
    s=18
)

plt.xlabel("Actual Freight Rate ($)")
plt.ylabel("Absolute Prediction Error ($)")
plt.title("Absolute Prediction Error vs Actual Freight Rate")

plt.tight_layout()
plt.show()

# ============================================================
# VISUALIZATION 5 — CATBOOST FEATURE IMPORTANCE
# ============================================================

feature_importance = pd.DataFrame({
    "feature": final_candidate_model.feature_names_,
    "importance": final_candidate_model.get_feature_importance()
})

feature_importance = feature_importance.sort_values(
    "importance",
    ascending=True
)

plt.figure(figsize=(10, 8))

plt.barh(
    feature_importance["feature"],
    feature_importance["importance"]
)

plt.xlabel("Feature Importance")
plt.ylabel("Feature")
plt.title("CatBoost Feature Importance")

plt.tight_layout()
plt.show()

print("Feature importance ranking:")
display(
    feature_importance.sort_values(
        "importance",
        ascending=False
    ).reset_index(drop=True)
)

# ============================================================
# VISUALIZATION 6 — MONTHLY PERFORMANCE
# ============================================================

monthly_results = pd.DataFrame({
    "month": validation_features["date"].dt.month.values,
    "actual": y_validation.values,
    "predicted": final_validation_predictions
})

monthly_summary = (
    monthly_results
    .groupby("month")
    .apply(
        lambda x: pd.Series({
            "MAE": mean_absolute_error(
                x["actual"],
                x["predicted"]
            ),
            "RMSE": np.sqrt(
                mean_squared_error(
                    x["actual"],
                    x["predicted"]
                )
            )
        }),
        include_groups=False
    )
    .reset_index()
)

print("Monthly performance:")
display(monthly_summary)

# Plot MAE
plt.figure(figsize=(8, 6))

plt.bar(
    monthly_summary["month"].astype(str),
    monthly_summary["MAE"]
)

plt.xlabel("Month")
plt.ylabel("MAE ($)")
plt.title("Validation MAE by Month")

plt.tight_layout()
plt.show()

# ============================================================
# FINAL VALIDATION PREDICTIONS CSV
# ============================================================

submission = pd.DataFrame({
    "load_id": validation_clean["load_id"].values,
    "predicted_rate": final_predictions
})

submission.to_csv(
    "validation_predictions.csv",
    index=False
)

print("FINAL CSV CREATED")
print("=" * 60)
print("Filename: validation_predictions.csv")
print("Shape:", submission.shape)
print("Columns:", submission.columns.tolist())

print("\nMissing values:")
print(submission.isna().sum())

print("\nDuplicate load IDs:")
print(submission["load_id"].duplicated().sum())

print("\nFirst 5 rows:")
display(submission.head())

# ============================================================
# FINAL PREDICTION SANITY CHECK
# ============================================================

print("FINAL PREDICTION SANITY CHECK")
print("=" * 60)

print("Number of predictions:", len(final_predictions))
print("Minimum prediction:   ", f"${final_predictions.min():,.2f}")
print("Maximum prediction:   ", f"${final_predictions.max():,.2f}")
print("Mean prediction:      ", f"${final_predictions.mean():,.2f}")
print("Median prediction:    ", f"${np.median(final_predictions):,.2f}")

print("\nNegative predictions:")
print((final_predictions < 0).sum())

print("\nMissing predictions:")
print(np.isnan(final_predictions).sum())

# ============================================================
# FINAL MODEL COMPARISON TABLE
# ============================================================

model_comparison = pd.DataFrame({
    "Model": [
        "Original CatBoost",
        "Log-target CatBoost",
        "Engineered CatBoost"
    ],
    "MAE": [
        111.62,
        114.52,
        119.18
    ],
    "RMSE": [
        632.73,
        635.84,
        633.45
    ],
    "R2": [
        0.8281,
        0.8264,
        0.8277
    ]
})

display(model_comparison)

# ============================================================
# FINAL MODEL METRICS
# ============================================================

print("FINAL SELECTED MODEL")
print("=" * 60)
print("Model: CatBoostRegressor")
print("Features: 18 original features")
print("Training rows: 38,477")
print("Validation rows: 9,523")
print("Best validation metrics:")
print(f"MAE  : ${111.62:,.2f}")
print(f"RMSE : ${632.73:,.2f}")
print(f"R²   : {0.8281:.4f}")

# ============================================================
# VISUALIZATION 7 — FINAL PREDICTION DISTRIBUTION
# ============================================================

plt.figure(figsize=(10, 6))

plt.hist(
    final_predictions,
    bins=50
)

plt.xlabel("Predicted Freight Rate ($)")
plt.ylabel("Number of Loads")
plt.title("Distribution of Final Predicted Freight Rates")

plt.tight_layout()
plt.show()

# ============================================================
# VISUALIZATION 8 — FINAL VALIDATION PREDICTION PERFORMANCE
# ============================================================

plt.figure(figsize=(10, 7))

plt.scatter(
    y_validation,
    final_validation_predictions,
    alpha=0.3,
    s=15
)

# Perfect prediction line
min_val = min(
    y_validation.min(),
    final_validation_predictions.min()
)

max_val = max(
    y_validation.max(),
    final_validation_predictions.max()
)

plt.plot(
    [min_val, max_val],
    [min_val, max_val],
    linestyle="--",
    linewidth=2,
    label="Perfect Prediction"
)

plt.xlabel("Actual Freight Rate ($)")
plt.ylabel("Predicted Freight Rate ($)")
plt.title("Final CatBoost: Actual vs Predicted Freight Rates")
plt.legend()

plt.tight_layout()
plt.show()

from google.colab import files

files.download("validation_predictions.csv")